[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@sp1-contracts/=lib/sp1-contracts/contracts",
    # Optimism Bedrock contracts live in packages/contracts-bedrock
    "src/libraries/=lib/optimism/packages/contracts-bedrock/src/libraries/",
    "src/L1/=lib/optimism/packages/contracts-bedrock/src/L1/",
    "src/L2/=lib/optimism/packages/contracts-bedrock/src/L2/",
    "src/dispute/=lib/optimism/packages/contracts-bedrock/src/dispute/",
    "src/cannon/=lib/optimism/packages/contracts-bedrock/src/cannon/",
    "interfaces/=lib/optimism/packages/contracts-bedrock/interfaces/",
    "@optimism/=lib/optimism/packages/contracts-bedrock/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
