apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "rollup-shared-publisher.fullname" . }}
  labels:
    {{ include "rollup-shared-publisher.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  target:
    name: {{ include "rollup-shared-publisher.fullname" . }}
  secretStoreRef:
    name: {{ .Values.vaultSecretStoreName }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.vaultSecretPath }}
        metadataPolicy: None