apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollup-shared-publisher.fullname" . }}
  labels:
    {{- include "rollup-shared-publisher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.port2 }}
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "rollup-shared-publisher.selectorLabels" . | nindent 4 }}
