name: Stage Tag Workflow
on:
  push:
    branches:
      - "prod-stage"
      - "feat/add-new-registry"
jobs:
  build-image-and-deploy:
    container:
      image: node:24
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Extract tag name
        id: extract_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: build image
        uses: ssvlabs/github-actions/actions/argo-workflow-submit@v0.2.0
        with:
          argo_workflow_file: .argo/build-image.yaml
          parameters: '["imageTag=${GITHUB_SHA}",
                      "dockerBuildExtraArgs="]'

      - name: deploy to prod hoodi
        uses: ssvlabs/github-actions/actions/argo-workflow-submit@v0.2.0
        with:
          argo_workflow_file: .argo/deploy.yaml
          parameters: '["gitopsRepo=gitops-production",
                      "imageTag=${GITHUB_SHA}",
                      "filePath=environments/aws/hoodi/compose/publisher.yaml"]'
  publish-charts:
    runs-on: self-hosted
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: github self-hosted runner workspace fix for 'tj-actions/changed-files'
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          dir_names_exclude_current_dir: true
          dir_names: true
          files: 'charts/**'
          files_ignore: |
            charts/*/Chart.yaml
            charts/*/CHANGELOG.md
      - name: publish chart via argo
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ssvlabs/github-actions/actions/argo-workflow-submit@v0.2.0
        with:
          argo_workflow_file: .argo/helmchart.yaml
          parameters: '["chartDirs=publisher"]'
