name: Workflow main
on:
  push:
    branches:
      - "stage-disabled"
jobs:
  build-image-and-deploy:
    container:
      image: node:24
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build image
        uses: ssvlabs/github-actions/actions/argo-workflow-submit@v0.2.0
        with:
          argo_workflow_file: .argo/build-image.yaml
          parameters: '["imageTag=${GITHUB_SHA}",
                      "dockerBuildExtraArgs="]'

      - name: deploy to stage hoodi
        uses: ssvlabs/github-actions/actions/argo-workflow-submit@v0.2.0
        with:
          argo_workflow_file: .argo/deploy.yaml
          parameters: '["gitopsRepo=gitops-stage",
                      "imageTag=${GITHUB_SHA}",
                      "filePath=environments/ovh/rollup/rollup-shared-publisher.yaml"]'
  publish-charts:
    runs-on: self-hosted
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: github self-hosted runner workspace fix for 'tj-actions/changed-files'
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          dir_names_exclude_current_dir: true
          dir_names: true
          files: 'charts/**'
          files_ignore: |
            charts/*/Chart.yaml
            charts/*/CHANGELOG.md
      - name: publish chart via argo
        uses: ssvlabs/github-actions/actions/argo-workflow-submit@v0.2.0
        with:
          argo_workflow_file: .argo/helmchart.yaml
          parameters: '["chartDirs=rollup-shared-publisher"]'
